// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO8ru2HgT_AIs25e3Jrr6TNWNa3LJua0A',
    appId: '1:431080313189:web:1004f0ddb812225d48918c',
    messagingSenderId: '431080313189',
    projectId: 'smartbin-c8ef7',
    authDomain: 'smartbin-c8ef7.firebaseapp.com',
    storageBucket: 'smartbin-c8ef7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8fvpryBTXb29KuHH-EdRwofJ2iZCats',
    appId: '1:431080313189:android:5dece616f3649ff748918c',
    messagingSenderId: '431080313189',
    projectId: 'smartbin-c8ef7',
    storageBucket: 'smartbin-c8ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZnDcVB18rtfk_sEcFJ5fzvxDdJhpcbg',
    appId: '1:431080313189:ios:0f6696d15a90fe4e48918c',
    messagingSenderId: '431080313189',
    projectId: 'smartbin-c8ef7',
    storageBucket: 'smartbin-c8ef7.firebasestorage.app',
    iosBundleId: 'com.example.smartBinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZnDcVB18rtfk_sEcFJ5fzvxDdJhpcbg',
    appId: '1:431080313189:ios:0f6696d15a90fe4e48918c',
    messagingSenderId: '431080313189',
    projectId: 'smartbin-c8ef7',
    storageBucket: 'smartbin-c8ef7.firebasestorage.app',
    iosBundleId: 'com.example.smartBinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO8ru2HgT_AIs25e3Jrr6TNWNa3LJua0A',
    appId: '1:431080313189:web:ec5d789291d3fb3e48918c',
    messagingSenderId: '431080313189',
    projectId: 'smartbin-c8ef7',
    authDomain: 'smartbin-c8ef7.firebaseapp.com',
    storageBucket: 'smartbin-c8ef7.firebasestorage.app',
  );
}
